# Generated by Django 6.0 on 2025-12-16 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='LovedOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this loved one relationship is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this loved one relationship was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this loved one relationship was last updated')),
                ('loved_one', models.ForeignKey(help_text='The user who is a loved one contact for the device owner', on_delete=django.db.models.deletion.CASCADE, related_name='loved_one_for', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The device owner who added this loved one contact', on_delete=django.db.models.deletion.CASCADE, related_name='loved_ones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loved One',
                'verbose_name_plural': 'Loved Ones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='core_lovedo_user_id_1f6b73_idx'), models.Index(fields=['loved_one'], name='core_lovedo_loved_o_507846_idx'), models.Index(fields=['user', 'is_active'], name='core_lovedo_user_id_7eaca9_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'loved_one'), name='unique_user_loved_one')],
            },
        ),
    ]
