# Generated by Django 6.0 on 2025-12-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lovedone'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(help_text='The JWT token string (stored for blacklist checking)', unique=True)),
                ('token_type', models.CharField(choices=[('refresh', 'Refresh'), ('email_verification', 'Email Verification'), ('password_reset', 'Password Reset')], help_text='Type of token (refresh, email_verification, password_reset)', max_length=50)),
                ('is_manually_blacklisted', models.BooleanField(default=False, help_text='Whether this token was manually blacklisted (vs expired)')),
                ('expires_at', models.DateTimeField(help_text="Token expiration time from JWT 'exp' claim")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this token was added to the blacklist')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this blacklist entry was last updated')),
            ],
            options={
                'verbose_name': 'Token Blacklist',
                'verbose_name_plural': 'Token Blacklist',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='core_tokenb_token_77467d_idx'), models.Index(fields=['token_type'], name='core_tokenb_token_t_dd5424_idx'), models.Index(fields=['expires_at'], name='core_tokenb_expires_3987f4_idx'), models.Index(fields=['token_type', 'expires_at'], name='core_tokenb_token_t_3b6281_idx')],
            },
        ),
    ]
