# Generated by Django 6.0 on 2025-12-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_crashevent_crash_altitude_crashevent_crash_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crashevent',
            name='gps_fix_at_crash',
        ),
        migrations.RemoveField(
            model_name='crashevent',
            name='satellites_at_crash',
        ),
        migrations.AddField(
            model_name='crashevent',
            name='gps_accuracy_at_crash',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crashevent',
            name='max_speed_before_crash',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crashevent',
            name='speed_at_crash',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crashevent',
            name='speed_change_at_crash',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
